# Qwen2-1.5B Big5 Psychology QLoRA Fine-tuning Configuration
# Optimized for M4 Pro 48GB with MPS support

### Model Configuration
model_name_or_path: Qwen/Qwen2-1.5B
stage: sft
do_train: true
finetuning_type: lora
quantization_bit: 4  # 4-bit quantization for memory efficiency
torch_dtype: fp16

### Dataset Configuration
dataset: big5_psychology
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### LoRA Configuration
lora_target: all
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.1
additional_target: embed_tokens,lm_head

### Training Configuration
output_dir: saves/qwen2-1.5b-big5-lora
logging_steps: 10
save_steps: 500
eval_steps: 500
evaluation_strategy: steps
save_strategy: steps
learning_rate: 5.0e-5
num_train_epochs: 5
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true
plot_loss: true
report_to: none
ddp_timeout: 180000000

### Optimization Configuration
optim: adamw_torch
weight_decay: 0.0
max_grad_norm: 1.0

### Evaluation Configuration
val_size: 0.1
per_device_eval_batch_size: 2
eval_accumulation_steps: 8
predict_with_generate: true

### Generation Configuration
do_sample: true
temperature: 0.7
top_p: 0.9
top_k: 50
num_beams: 1
repetition_penalty: 1.1

### Hardware Configuration
ddp_find_unused_parameters: false
ddp_bucket_cap_mb: 25
ddp_broadcast_buffers: false
dataloader_pin_memory: true
remove_unused_columns: false

### Logging Configuration
logging_dir: logs/qwen2-big5-qlora
logging_first_step: true
logging_nan_inf_filter: true